Models/About.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Portfolyom.Models
{
    public class About
    {
        public int Id { get; set; }
        public string About_Desc { get; set; }
        public string Image { get; set; }
    }
}

Models/Admin.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Portfolyom.Models
{
    public class Admin
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}

Models/CartInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Portfolyom.Models
{
    public class CartInfo
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Title { get; set; }
        public string Experience { get; set; }
    }
}

Models/Contact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Portfolyom.Models
{
    public class Contact
    {
        public int Id { get; set; }
        public int Name_Surname { get; set; }
        public int Subject { get; set; }
        public int Message { get; set; }
    }
}

Models/Context.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Portfolyom.Models
{
    public class Context:DbContext
    {
        public virtual DbSet<About> Abouts {get; set;}
        public virtual DbSet<CartInfo> CartInfos {get; set;}
        public virtual DbSet<Experience> Experiences {get; set;}
        public virtual DbSet<Project> Projects {get; set;}
        public virtual DbSet<Contact> Contacts {get; set;}
        public virtual DbSet<Admin> Admins {get; set;}
    }
}

Models/Experience.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Portfolyom.Models
{
    public class Experience
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Models/Project.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Portfolyom.Models
{
    public class Project
    {
        public int Id { get; set; }
        public string Project_Name { get; set; }
        public string Project_Image { get; set; }
        public string Project_Url { get; set; }
        public string Project_Info { get; set; }
    }
}

Controllers/AdminControlController.cs
using Portfolyom.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Portfolyom.Controllers
{
    public class AdminControlController : Controller
    {
        Context c = new Context();
        [Authorize]
        public ActionResult Home()
        {
            return View(c.CartInfos.ToList());
        }

        [Authorize]
        public ActionResult HomeIcerikSil(int id)
        {
            var bul = c.CartInfos.Find(id);
            c.CartInfos.Remove(bul);
            c.SaveChanges();
            return RedirectToAction("Home", "AdminControl");
        }
        [HttpGet]
        [Authorize]
        public ActionResult HomeGuncelle(int id)
        {
            var bul = c.CartInfos.Find(id);
            return View(bul);
        }
        [HttpPost]
        [Authorize]
        public ActionResult HomeGuncelle(CartInfo p)
        {
            var data = c.CartInfos.Where(x => x.Id == p.Id).SingleOrDefault();
            data.Title = p.Title;
            data.Id = p.Id;
            data.Image = p.Image;
            c.SaveChanges();
            return RedirectToAction("Home", "AdminControl");
        }

        //--------------------------------------------------------------------Home Kismi

        [Authorize]
        public ActionResult About()
        {
            return View(c.Abouts.ToList());
        }

        [Authorize]
        public ActionResult AboutIcerikSil(int id)
        {
            var bul = c.Abouts.Find(id);
            c.Abouts.Remove(bul);
            c.SaveChanges();
            return RedirectToAction("Home", "AdminControl");
        }

        [HttpGet]
        [Authorize]
        public ActionResult AboutGuncelle(int id)
        {
            var bul = c.Abouts.Find(id);
            return View(bul);
        }

        [HttpPost]
        [Authorize]
        public ActionResult AboutGuncelle(About p)
        {
            var data = c.Abouts.Where(x => x.Id == p.Id).SingleOrDefault();
            data.Id = p.Id;
            data.Image = p.Image;
            data.About_Desc = p.About_Desc;
            data.About_Desc = p.About_Desc;
            c.SaveChanges();
            return RedirectToAction("Home", "AdminControl");
        }

        //--------------------------------------------------------------------About Kismi
        [Authorize]
        public ActionResult Project()
        {
            return View(c.Projects.ToList());
        }

        [Authorize]
        public ActionResult Contact()
        {
            return View(c.Contacts.ToList());
        }
    }
}

Controllers/AnaSayfaController.cs
using Portfolyom.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Portfolyom.Controllers
{
    public class AnaSayfaController : Controller
    {
        Context c = new Context();
        public ActionResult Index()
        {
            return View(c.CartInfos.ToList());
        }

        public ActionResult About()
        {
            return View(c.Abouts.ToList());
        }

        public ActionResult Projects()
        {
            return View(c.Projects.ToList());
        }

        public ActionResult Contact()
        {
            return View();
        }


    }
}

Controllers/LoginController.cs
using Portfolyom.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Portfolyom.Controllers
{
    public class LoginController : Controller
    {
        Context c = new Context();
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Admin login)
        {
            var kullanici = c.Admins.FirstOrDefault(x => x.UserName == login.UserName && x.Password == login.Password);
            if (kullanici != null)
            {
                FormsAuthentication.SetAuthCookie(kullanici.UserName, false);
                Session["Username"] = kullanici.UserName.ToString();
                return RedirectToAction("Home", "AdminControl");
            }
            else
            {
                return View();
            }

        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Response.Cookies["ASP.NET_SessionId"].Expires = DateTime.Now.AddDays(-1);
            return RedirectToAction("Index", "Login");
        }
    }
}

Views/AdminControl/About.cshtml
@model List<Portfolyom.Models.About>
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Anasayfa İçerik Kontrolü</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->

        <div class="container-fluid">
            <!-- Small boxes (Stat box) -->

            <div class="card">
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>İd</th>
                                <th>Açıklama</th>
                                <th>Resim</th>
                                <th>İşlemler</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.About_Desc</td>
                                    <td> <img style="height:70px; width:70px;" src="@item.Image" /></td>
                                    <td>
                                        @*<a style="margin-right: 4px;" href="/Admin/OdaTipleri/YeniOdaTipi" class="btn btn-tbl-edit btn-xs btn-secondary" title="Ekle"><i class="fa-solid fa-plus"></i></a>*@
                                        <a style="margin-right: 4px;" href="/AdminControl/AboutGuncelle/@item.Id" class="btn btn-tbl-edit btn-xs btn-secondary" title="Düzenle"><i class="fa-solid fa-pencil"></i></a>
                                        <a style="margin-right: 4px;" href="/AdminControl/AboutIcerikSil/@item.Id" class="btn btn-tbl-edit btn-xs btn-danger" title="Sil"><i class="fa-solid fa-trash"></i></a>
                                    </td>
                                </tr>

                            }

                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.content-wrapper -->
            <!-- Control Sidebar -->
            <aside class="control-sidebar control-sidebar-dark">
                <!-- Control sidebar content goes here -->
            </aside>
            <!-- /.control-sidebar -->
        </div>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
</section>

Views/AnaSayfa/Index.cshtml
@model List<Portfolyom.Models.CartInfo>
@{
    Layout = "~/Views/Shared/_MyLayout .cshtml";
}

<!DOCTYPE html>
<html lang="tr">

<!-- Mirrored from wpriverthemes.com/landing/gridx-html/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 29 May 2023 13:50:48 GMT -->

<body>

    <main class="main-homepage">

        <!-- Header -->
       

        <!-- About -->
        <section class="about-area">
            <div class="container">
                <div class="row">
                    @foreach (var item in Model)
                    {
                        <div class="col-md-6" data-aos="zoom-in">
                            <div class="about-me-box shadow-box">
                                <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/bg1.png" alt="BG" class="bg-img">
                                <div class="img-box">
                                    <img src="@item.Image" alt="About Me">
                                </div>
                                <div class="infos">
                                    <h4>@item.Title</h4>
                                    <h1>AHMET CAN CEYLAN</h1>
                                    <p>Full Stack Developer</p>
                                    <a href="@Url.Action("Index", "Login")">.</a>
                                </div>
                            </div>
                        </div>
                    }
                    <div class="col-md-6">
                        <div class="about-credentials-wrap">
                            <div data-aos="zoom-in">
                                <div class="banner shadow-box">
                                    <div class="marquee">
                                        <div>
                                            <span><b>CSS</b> <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/star1.svg" alt="Star"><b>HTML</b> <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/star1.svg" alt="Star"><b>C#</b> <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/star1.svg" alt="Star"><b>.Net Mvc</b><img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/star1.svg" alt="Star"><b>Jquery</b><img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/star1.svg" alt="Star"><b>GoLang</b> <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/star1.svg" alt="Star"><b>C</b> <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/star1.svg" alt="Star"><b>JavaScript</b> <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/star1.svg" alt="Star"><b>Entity Framework</b> <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/star1.svg" alt="Star"><b>Visual Studio</b> <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/star1.svg" alt="Star"><b>Visual Studio Code</b> <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/star1.svg" alt="Star"><b>React</b> <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/star1.svg" alt="Star"><b>React Native</b> <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/star1.svg" alt="Star"></span>
                                        </div>
                                    </div>
                                </div>

                            </div>

                            <div class="gx-row d-flex gap-24">
                                <div data-aos="zoom-in">
                                    <div class="about-crenditials-box info-box shadow-box h-full">
                                        <a class="overlay-link" href="@Url.Action("About", "AnaSayfa")"></a>
                                        <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/bg1.png" alt="BG" class="bg-img">
                                        <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/sign.png" alt="Sign">
                                        <div class="d-flex align-items-center justify-content-between">
                                            <div class="infos">
                                                <h1>Bilgiler</h1>
                                            </div>

                                            <a class="about-btn">
                                                <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/icon.svg" alt="Button">
                                            </a>

                                        </div>
                                    </div>
                                </div>

                                <div data-aos="zoom-in">
                                    <div class="about-project-box info-box shadow-box h-full">
                                        <a class="overlay-link" href="@Url.Action("Projects", "AnaSayfa")"></a>
                                        <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/bg1.png" alt="BG" class="bg-img">
                                        <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/my-works.png" alt="My Works">
                                        <div class="d-flex align-items-center justify-content-between">
                                            <div class="infos">
                                                <h1>Projeler</h1>
                                            </div>

                                            <a href="#" class="about-btn">
                                                <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/icon.svg" alt="Button">
                                            </a>

                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

                <div class="row mt-24">
                    <div class="col-md-12">
                        <div class="blog-service-profile-wrap d-flex gap-24">
                            

                            <div data-aos="zoom-in" class="flex-1">
                                <div class="about-services-box info-box shadow-box h-full">
                                    <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/bg1.png" alt="BG" class="bg-img">
                                    <div class="icon-boxes">
                                        <i class="iconoir-code"></i>
                                        <i class="iconoir-design-pencil"></i>
                                        <i class="iconoir-web-window"></i>
                                        <i class="iconoir-dev-mode-phone"></i>
                                    </div>
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div class="infos">
                                        </div>
                                    </div>
                                </div>
                            </div>

                            
                                <div class="about-profile-box info-box shadow-box h-full">
                                    <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/bg1.png" alt="BG" class="bg-img">
                                    <div class="inner-profile-icons shadow-box">
                                        <a href="https://www.linkedin.com/in/ahmet-can-ceylan/" target="_blank">
                                            <i class="iconoir-linkedin"></i>
                                        </a>

                                        <a href="mailto:ahmetcanceylann81@gmail.com">
                                            <i class="iconoir-send-mail"></i>
                                        </a>

                                        <a href="https://github.com/IACCI" target="_blank">
                                            <i class="iconoir-github"></i>
                                        </a>
                                    </div>
                                </div>
                            

                        </div>
                    </div>

                </div>

                <div class="row mt-24">
                    <div class="col-md-6" data-aos="zoom-in">

                        <div class="about-client-box info-box shadow-box">
                            <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/bg1.png" alt="BG" class="bg-img">
                            <div class="clients d-flex align-items-start gap-24 justify-content-center">
                                <div class="client-item">
                                    <h1>03</h1>
                                    <p>Yıl <br>Deneyim</p>
                                </div>

                                <div class="client-item">
                                    <h1>+10</h1>
                                    <p>Müşteri</p>
                                </div>

                                <div class="client-item">
                                    <h1>+20</h1>
                                    <p>Toplam <br>Proje</p>
                                </div>
                            </div>
                        </div>

                    </div>
                    @*<div class="col-md-6" data-aos="zoom-in">

                        <div class="about-contact-box info-box shadow-box">
                            <a class="overlay-link" href="contact.html"></a>
                            <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/bg1.png" alt="BG" class="bg-img">
                            <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/icon2.png" alt="Icon" class="star-icon">
                            <h1>Let's <br>work <span>together.</span></h1>
                            <a href="#" class="about-btn">
                                <img src="~/Content/PortfolyoProject/wpriverthemes.com/landing/gridx-html/assets/images/icon.svg" alt="Button">
                            </a>
                        </div>

                    </div>*@
                </div>
            </div>
        </section>

        <!-- Footer -->
       

    </main>
</body>

<!-- Mirrored from wpriverthemes.com/landing/gridx-html/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 29 May 2023 13:50:55 GMT -->
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Dashboard</title>
    <link href="~/Admin/assets/plugins/datatables/plugins/bootstrap/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Content/AdminPanel/plugins/fontawesome-free/css/all.min.css">

    <link href="~/Admin/assets/plugins/datatables/plugins/bootstrap/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/Content/AdminPanel/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/Content/AdminPanel/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/Content/AdminPanel/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/AdminPanel/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/Content/AdminPanel/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/Content/AdminPanel/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/Content/AdminPanel/plugins/summernote/summernote-bs4.min.css">
</head>

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                </li>
            </ul>

            <!-- Right navbar links -->
        </nav>
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="#" class="brand-link">
                <img src="~/Content/AdminPanel/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">Kontrol Paneli</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">

                        <img src="~/Content/Images/cvyeyeni (1).jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Ahmet Can Ceylan</a>
                    </div>
                </div>

                <!-- SidebarSearch Form -->
                <div class="form-inline">
                    <div class="input-group" data-widget="sidebar-search">
                        <input class="form-control form-control-sidebar" type="search" placeholder="Ara" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-sidebar">
                                <i class="fas fa-search fa-fw"></i>
                            </button>
                        </div>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->

                        <li class="nav-item">
                            <a href="/AdminControl/Home" class="nav-link">
                                <i class="nav-icon fas fa-columns"></i>
                                <p>
                                    Ana Sayfa
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/AdminControl/About" class="nav-link">
                                <i class="nav-icon fas fa-columns"></i>
                                <p>
                                    Hakkımızda
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/AdminControl/Project" class="nav-link">
                                <i class="nav-icon fas fa-columns"></i>
                                <p>
                                    Projeler
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/AdminControl/Contact" class="nav-link">
                                <i class="nav-icon fas fa-columns"></i>
                                <p>
                                    İletişim
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "AnaSayfa")" class="nav-link">
                                <i class="nav-icon fas fa-columns"></i>
                                <p>
                                    Siteye Git
                                </p>
                            </a>
                        </li>

                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <div class="content-wrapper">
            @RenderBody()
        </div>

        <footer class="main-footer">
            @*<div class="float-right d-none d-sm-block">

                </div>*@
            <strong>Copyright &copy; @DateTime.Today.Year </strong> Tüm hakları saklıdır.
        </footer>
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>

    <script src="~/Content/AdminPanel/plugins/datatables/jquery.dataTables.js"></script>
    <script src="~/Content/AdminPanel/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Content/AdminPanel/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Content/AdminPanel/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/Content/AdminPanel/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/Content/AdminPanel/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/Content/AdminPanel/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/Content/AdminPanel/plugins/jszip/jszip.min.js"></script>
    <script src="~/Content/AdminPanel/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/Content/AdminPanel/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/Content/AdminPanel/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/Content/AdminPanel/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/Content/AdminPanel/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    <!-- jQuery -->
    <script src="~/Content/AdminPanel/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/Content/AdminPanel/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>$.widget.bridge('uibutton', $.ui.button)</script>
    <!-- Bootstrap 4 -->
    <script src="~/Content/AdminPanel/bootstrap/js/bootstrap-datepicker.js"></script>
    <script src="~/Content/AdminPanel/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="~/Content/AdminPanel/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/Content/AdminPanel/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/Content/AdminPanel/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/Content/AdminPanel/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/Content/AdminPanel/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/Content/AdminPanel/plugins/moment/moment.min.js"></script>
    <script src="~/Content/AdminPanel/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/Content/AdminPanel/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/Content/AdminPanel/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/Content/AdminPanel/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/AdminPanel/dist/js/adminlte.js"></script>

    <script src="~/Content/AdminPanel/assets/plugins/sweet-alert/sweetalert2.all.min.js"></script>


</body>
</html>